name: dogsite
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  google_fonts: ^5.0.0
  flutter:
    sdk: flutter
     

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/1 (1).jpg
  - assets/2.jpg
  
